//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanCodeWiki
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CleanCodeEntities : DbContext
    {
        public CleanCodeEntities()
            : base("name=CleanCodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<article> articles { get; set; }
        public DbSet<article_tag> article_tag { get; set; }
        public DbSet<article_user> article_user { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<tag> tags { get; set; }
        public DbSet<user> users { get; set; }
    }
}
