//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanCodeWiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag
    {
        public tag()
        {
            this.article_tag = new HashSet<article_tag>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<article_tag> article_tag { get; set; }
    }
}
