//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanCodeWiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.article_user = new HashSet<article_user>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public byte[] password { get; set; }
        public byte[] salt { get; set; }
        public sbyte role_id { get; set; }
    
        public virtual ICollection<article_user> article_user { get; set; }
        public virtual role role { get; set; }
    }
}
